server:  port: 8191

#spring.datasource.url = jdbc:mysql://localhost:3306/sbdb?useSSL=falsespring:  datasource:    url:  jdbc:mysql://localhost:3306/msdb?allowPublicKeyRetrieval=true&useSSL=false    username: root    password: root
  jpa:    properties:      hibernate:       dialect: org.hibernate.dialect.MySQL5InnoDBDialect    hibernate:      ddl-auto: update  
  profiles:    active: dev
management:  endpoints:    web:      exposure:        exclude:         - =*

